import { Card } from './types/card';

// クイズカードのデータ例
export const CARDS: Card[] = [
  {
    id: 1,
    quiz_img: '画像1',
    text: 'テキスト1',
    CorrectType: 'correct',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト1',
  },
  {
    id: 2,
    quiz_img: '画像2',
    text: 'テキスト2',
    CorrectType: 'incorrect',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト2',
  },
  {
    id: 3,
    quiz_img: '画像3',
    text: 'テキスト3',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト3',
  },
  {
    id: 4,
    quiz_img: '画像4',
    text: 'テキスト4',
    CorrectType: 'correct',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト4',
  },
  {
    id: 5,
    quiz_img: '画像5',
    text: 'テキスト5',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト5',
  },
  {
    id: 6,
    quiz_img: '画像6',
    text: 'テキスト6',
    CorrectType: 'correct',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト6',
  },
  {
    id: 7,
    quiz_img: '画像7',
    text: 'テキスト7',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト7',
  },
  {
    id: 8,
    quiz_img: '画像8',
    text: 'テキスト8',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト8',
  },
  {
    id: 9,
    quiz_img: '画像9',
    text: 'テキスト9',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト9',
  },
  {
    id: 10,
    quiz_img: '画像10',
    text: 'テキスト10',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト10',
  },
  {
    id: 11,
    quiz_img: '画像11',
    text: 'テキスト11',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト11',
  },
  {
    id: 12,
    quiz_img: '画像12',
    text: 'テキスト12',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト12',
  },
  {
    id: 13,
    quiz_img: '画像13',
    text: 'テキスト13',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト13',
  },
  {
    id: 14,
    quiz_img: '画像14',
    text: 'テキスト14',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト14',
  },
  {
    id: 15,
    quiz_img: '画像15',
    text: 'テキスト15',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト15',
  },
  {
    id: 16,
    quiz_img: '画像16',
    text: 'テキスト16',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト16',
  },
  {
    id: 17,
    quiz_img: '画像17',
    text: 'テキスト17',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト17',
  },
  {
    id: 18,
    quiz_img: '画像18',
    text: 'テキスト18',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト18',
  },
  {
    id: 19,
    quiz_img: '画像19',
    text: 'テキスト19',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト19',
  },
  {
    id: 20,
    quiz_img: '画像20',
    text: 'テキスト20',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト20',
  },
  {
    id: 21,
    quiz_img: '画像21',
    text: 'テキスト21',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト21',
  },
  {
    id: 22,
    quiz_img: '画像22',
    text: 'テキスト22',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト22',
  },
  {
    id: 23,
    quiz_img: '画像23',
    text: 'テキスト23',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト23',
  },
  {
    id: 24,
    quiz_img: '画像24',
    text: 'テキスト24',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト24',
  },
  {
    id: 25,
    quiz_img: '画像25',
    text: 'テキスト25',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト25',
  },
  {
    id: 26,
    quiz_img: '画像26',
    text: 'テキスト26',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト26',
  },
];
