import { Card } from './types/card';

// クイズカードのデータ例
export const CARDS: Card[] = [
  {
    quiz_img: '画像1',
    text: 'テキスト1',
    CorrectType: 'correct',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト1',
  },
  {
    quiz_img: '画像2',
    text: 'テキスト2',
    CorrectType: 'incorrect',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト2',
  },
  {
    quiz_img: '画像3',
    text: 'テキスト3',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト3',
  },
  {
    quiz_img: '画像4',
    text: 'テキスト4',
    CorrectType: 'correct',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト4',
  },
  {
    quiz_img: '画像5',
    text: 'テキスト5',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト5',
  },
  {
    quiz_img: '画像6',
    text: 'テキスト6',
    CorrectType: 'correct',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト6',
  },
  {
    quiz_img: '画像7',
    text: 'テキスト7',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト7',
  },
  {
    quiz_img: '画像8',
    text: 'テキスト8',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト8',
  },
  {
    quiz_img: '画像9',
    text: 'テキスト9',
    CorrectType: 'correct',
    cardType: 'drivers-license',
    isAddedToReview: false,
    explanation: '解説テキスト9',
  },
  {
    quiz_img: '画像10',
    text: 'テキスト10',
    CorrectType: 'incorrect',
    cardType: 'provisional-license',
    isAddedToReview: false,
    explanation: '解説テキスト10',
  },
];
